name: totp_authenticator
description: A Flutter (dart) package to generate and verify Time-based One-Time Passwords (TOTP) that works with authenticator apps like Google Authenticator, Microsoft Authenticator, and more.
version: 1.0.1
repository: https://github.com/leonimeloo/totp_authenticator

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.6
  base32: ^2.1.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
